[tool.poetry]
name = "doit"
version = "0.1.0"
description = "A TUI todo manager"
authors = ["kraanzu <kraanzu@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
textual = "^0.1.17"
pyperclip = "^1.8.2"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
