[tool.poetry]
name = "dooit"
version = "2.2.0"
description = "A TUI todo manager"
authors = ["kraanzu <kraanzu@gmail.com>"]
maintainers = ["kraanzu <kraanzu@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/kraanzu/dooit"
repository = "https://github.com/kraanzu/dooit"
exclude = ["imgs"]

[tool.poetry.dependencies]
python = "^3.8"
pyperclip = "^1.8.2"
PyYAML = "^6.0"
tzlocal = "2.1"
appdirs = "^1.4.4"
textual = "^0.73.0"
python-dateutil = "^2.8.2"
msgpack = "^1.0.7"
multidict = "^6.0.5"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.261"
black = "^23.3.0"
pre-commit = "^3.2.2"
textual-dev = "^1.1.0"
mkdocs = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
dooit = 'dooit.__main__:main'
