[tool.poetry]
name = "dooit"
version = "1.0.0"
description = "A TUI todo manager"
authors = ["kraanzu <kraanzu@gmail.com>"]
maintainers = ["kraanzu <kraanzu@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/kraanzu/dooit"
repository = "https://github.com/kraanzu/dooit"

[tool.poetry.dependencies]
python = "^3.8"
textual = "^0.12.1"
pyperclip = "^1.8.2"
PyYAML = "^6.0"
dateparser = "^1.1.2"
tzlocal = "2.1"
appdirs = "^1.4.4"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
flake8 = "^4.0.1"
pre-commit = "^2.19.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
dooit = 'dooit.__init__:main'
